### ISSUE TITLE
Sound does not grow

### ISSUE THREAD

**Issue by torakiti2017** [akira0245/MidiBard#10]
I'm playing with an external Midi keyboard connected.
When you hold down the key, the sound may not be extended.
It's hard to explain, but when you play each key in succession. (Is it an arpeggio?)
・ "C ～": OK
・ "C ～ D ～ E ～": OK
・ "CDE ～": NG ("E" does not grow)

**Comment by akira0245** [comment]
looking into it, thank you.

**Comment by akira0245** [comment]
@torakiti2017 this should be fixed in 1.7.0.0 too.

**Comment by torakiti2017** [comment]
・Sound does not grow
I was able to confirm the operation. thank you!
