### ISSUE TITLE
When I select an electric guitar in "instrument" and switch it, the UI of FF14 does not follow.

### ISSUE THREAD

**Issue by torakiti2017** [akira0245/MidiBard#14]
When I select an electric guitar in "instrument" and switch it, the UI of FF14 does not follow.
There is no problem as it is.
But is it a special switching method?
(I'm worried that the FF14 team will point out.)

<img width="383" alt="1" src="https://user-images.githubusercontent.com/86459831/135012926-b2365d19-4a05-4ed6-9256-09a807f2d8b1.png">
<img width="369" alt="2" src="https://user-images.githubusercontent.com/86459831/135012955-2a1fe367-6be4-4fea-aa27-2bc96afdd2fc.png">

**Comment by akira0245** [comment]
Yes this is an issue of current tone switching method, however in server or other people's perspective there's no difference. i'll take a look for a possible UI refresh.

**Comment by torakiti2017** [comment]
Please consider it. thank you.

**Comment by akira0245** [comment]
@torakiti2017 the game tone UI should be update when Midibard performs a tone change now.
