### ISSUE TITLE
An error occurs when operating the "player control panel"

### ISSUE THREAD

**Issue by torakiti2017** [akira0245/MidiBard#16]
1. Make sure the song is selected in the playlist.
![1](https://user-images.githubusercontent.com/86459831/135573422-ae3b7bd0-9a74-45f2-99ae-8a6f17357dca.jpg)

2. Turn off the "Toggle settings panel".
![2](https://user-images.githubusercontent.com/86459831/135573442-ac4f0180-b5b9-4e73-bd39-a99da05f9176.jpg)

3. Turn off "Toggle player control panel".
![3](https://user-images.githubusercontent.com/86459831/135573457-30df3c42-2dcb-4619-8438-18f0bdbf43d0.jpg)

4. Turn on "Toggle player control panel".
![Error](https://user-images.githubusercontent.com/86459831/135573538-89e2d36e-b70c-48af-a56a-efabc2d9e8eb.jpg)

**Comment by akira0245** [comment]
fixed in new build. Thank you.
