### ISSUE TITLE
External midi automatic switching of "input Device"

### ISSUE THREAD

**Issue by torakiti2017** [akira0245/MidiBard#17]
Normally, "None" is selected for "input Device", but is it possible to switch to them automatically when an external midi is detected / connected?
The content of the "settings panel" does not change much once it is set, so I would like to hide it, but that is not the case because it is necessary to select an external midi.
Some people may not like to switch automatically, so it is desirable to be able to select it as an option.

**Comment by akira0245** [comment]
yes this would be possible. it now should save the last used midi device's name and switch back to it when starting. also would provide an option for auto start listening new input device when one appearing.

**Comment by akira0245** [comment]
@torakiti2017 have pushed an update to the repo. feel free to report any issue you met.

**Comment by torakiti2017** [comment]
Thank you for your measures.
There was no problem with the operation when logging in to FF14 with an external MIDI keyboard connected.
The question is, is it impossible to detect and connect external MIDI during the game?
My usage is that I don't always connect external MIDI, but when I play, I connect external MIDI. (Sorry for requests due to personal environment and usage.)

**Comment by akira0245** [comment]
>  is it impossible to detect and connect external MIDI during the game?

Yes it's possible, and the plugin is always scanning for new devices during game running. 
All detected midi input devices should appears immediately in plugin's `Input device` selection list. If your midi keyboard didn't show in the list, there's not much i can do. But if it does appear in the list but not auto connected, there're some possible situations.

Once a new input device is detected (and the plugin is not listening existing device), then it will try connect to the first appeared device. **it won't try connect to a new device when already in listening mode**. 
And if two midi devices are detected at the same time, it only will try to connect to the first detected one.
Also please make sure the `Auto listening new device` checkbox is on. @torakiti2017

**Comment by akira0245** [comment]
Do you have multiple midi device used for bard or just have one frequently used device? Maybe i can change the default behavior to always trying to reconnect last used midi device.

**Comment by torakiti2017** [comment]
> Also please make sure the Auto listening new device checkbox is on.

Both "Restore device on start" and "Auto listening new device" are ON.

> Do you have multiple midi device used for bard or just have one frequently used device?

Only one MIDI device is used.


In my environment, the behavior is as follows.
<Pattern 1>
1. Start "Perform"
  * "Input Device": X3mini
  * "Input Device" list: None, X3mini
  * Performance using an external MIDI keyboard is possible
2. Unplug the external MIDI cable (external MIDI not connected)
  * "Input Device": X3mini
  * "Input Device" list: None
3. External MIDI connection
  * "Input Device": X3mini
  * "Input Device" list: None, X3mini
  * Performance using an external MIDI keyboard is not possible

<Pattern 2>
1. Start "Perform"
  * "Input Device": X3mini
  * "Input Device" list: None, X3mini
  * Performance using an external MIDI keyboard is possible
2. Unplug the external MIDI cable (external MIDI not connected)
  * "Input Device": X3mini
  * "Input Device" list: None
3. End of "Perform"
4. External MIDI connection
5. Start "Perform"
  * "Input Device": X3mini
  * "Input Device" list: None, X3mini
  * Performance using an external MIDI keyboard is not possible

**Comment by akira0245** [comment]
I see the problem. the plugin didn't dispose midi devices which is already disconnected. Because it's listening to a non-existing device reference, it also won't try detect new devices.
please try the new version to see if it resolves your problem.

**Comment by akira0245** [comment]
I removed the `Auto listening new device` option because it's bit of redundant. Now if you have `Auto restart listening` enabled,  midibard will always trying to scan and reconnect the last used midi device whenever it appears.

**Comment by torakiti2017** [comment]
It works as expected.
Thank you for your support!
