### ISSUE TITLE
The plugin installer ran into an issue..

### ISSUE THREAD

**Issue by Squishydew** [akira0245/MidiBard#19]
I'm new to Midibard and tried to install it but get this error:

The plugin installer ran into an issue or the plugin is incompatible.
Please restart the game and report this error on our discord.

It did create a midibard folder in XIVLauncher/installedPlugins but after closing the game, deleting said folder, launching the game and trying to install it again i get the same error.
![Untitled](https://user-images.githubusercontent.com/91894402/135863480-6ba76593-5cc8-450b-ba16-3ec520f63ce3.png)

**Comment by akira0245** [comment]
@Squishydew the repo URL you used is for a newer dalamud version,
 you could enable dalamud testing https://github.com/akira0245/MidiBard/issues/11#issuecomment-924003440 to use this api4 repo 
Or use api3 Repo: `https://raw.githubusercontent.com/akira0245/DalamudPlugins/cn/pluginmaster.json`   temporarily before dalamud updates.
