### ISSUE TITLE
    》 MidiBard update to v1.5.0.2 failed.

### ISSUE THREAD

**Issue by BaronSolace** [akira0245/MidiBard#2]
"The plugin installer ran into an issue or the plugin is incompatible.
please restart the game and report this error on our discord"

got this error,  rebooted the game and problem still persists

**Comment by akira0245** [comment]
try delete `..\XIVLauncher\installedPlugins\MidiBard` folder then restart game, install the new version. see if the problem persists.

**Comment by BaronSolace** [comment]
new update worked.  thank you
