### ISSUE TITLE
无法安装MidiBard

### ISSUE THREAD

**Issue by lunadece** [akira0245/MidiBard#26]
您好,一直很喜欢使用您开发的MidiBard在FF14里面演奏,也感谢您辛苦开发如此出色的插件并无私分享给大家使用!!
我忽然遇到在游戏中无法安装的问题,请问是我的问题还是必须等插件更新呢?谢谢您的回复
![b0e5babb7590bddfd9c9538353fa105](https://user-images.githubusercontent.com/92234680/136676111-b0cbabdb-ae67-45de-b80a-faf067f9dfe4.png)

**Comment by akira0245** [comment]
嗯…… 插件应该不用更新是可以正常安装的，可以试一下关掉游戏之后把卫月目录里`\XIVLauncher\installedPlugins\MidiBard`这个文件夹删掉之后重启游戏再安装，还是不行的话可以发一下卫月dll目录里的dalamud.log文件

**Comment by lunadece** [comment]
刚刚又重新试了一下,已经可以安装了,非常感谢..另外,我发现您是否将单人在电吉他演奏下,双音轨可以分开选择音色演奏的这个功能(bug?)给修正了?..现在双音轨只能同时选择一种音色表演..其实我自己玩起来是觉得还满有趣的..总之非常感谢您的辛苦付出,MidiBard真的很好用,我玩FF14至少有一半是因为这个演奏功能..谢谢~
