### ISSUE TITLE
This plugin breaks attaching a debugger to FFXIV for me

### ISSUE THREAD

**Issue by Zeffuro** [akira0245/MidiBard#28]
Having this plugin installed crashes the game when trying to attach a debugger through Rider and Visual Studio for me.
I think it was causing issues with IDA as well but I'm not 100% about that part.

I tried only having this plugin installed and the other plugin I'm trying to debug installed and still caused issues (and it only fixes itself after uninstall MidiBard and restarting the game).

According to goat: "but C# 9 function pointers have a nasty catch, you have to declare them as delegate* unmanaged or the CLR engine will crash"

![rider64_2021-10-14_16-02-45](https://user-images.githubusercontent.com/4972345/137350536-483179d8-37b2-4da9-91a1-0acdbad89459.png)

```
System.ExecutionEngineException
  HResult=0x80131506
  Message=Exception_WasThrown
```

`An IL variable is not available at the current native IP. The error code is CORDBG_E_IL_VAR_NOT_AVAILABLE, or 0x80131304.`

**Comment by akira0245** [comment]
Thanks for the report, this issue may caused by the dependent dll, should be fixed in new build.

**Comment by Zeffuro** [comment]
I've tested the new build and I can confirm this fully fixes the issue for me, thanks for making this awesome plugin.
I use this with my actual Keyboard and it works fine <3
