### ISSUE TITLE
1.9.2.4 midibard broke guitar tone override mode

### ISSUE THREAD

**Issue by Caliel666** [akira0245/MidiBard#32]
in 1.9.2.4:
https://user-images.githubusercontent.com/38433434/143326956-7ec05624-2c3f-400f-aa3a-a819c47cfbb8.mp4

in 1.9.2.3:
https://user-images.githubusercontent.com/38433434/143328392-dbf28795-ac43-4012-a479-cd9094de9acb.mp4

**Comment by akira0245** [comment]
oop sorry for this, i think i broke something when tinker with midi channels stuff, now the changes has been reverted, thank you.

**Comment by Caliel666** [comment]
all working now! thank you so much for your time
