### ISSUE TITLE
FFXIV6.0 (api5?)compatible

### ISSUE THREAD

**Issue by torakiti2017** [akira0245/MidiBard#36]
Are there any plans to support FFXIV6.0 (api5?)?
I'm always using it, so I'm looking forward to it.

**Comment by torakiti2017** [comment]
sorry...
After checking it earlier, it can be used in my environment.

**Comment by akira0245** [comment]
just pushed an update for api5, please let me know if you have any issues

**Comment by torakiti2017** [comment]
Thank you!
I will use it again!
