### ISSUE TITLE
Standard tone switching broken

### ISSUE THREAD

**Issue by bilenkonito** [akira0245/MidiBard#37]
Standard tone switching currently only loads the first ProgramChange event from the first channel.
I would investigate and fix this myself but it looks like the repo is missing the last couple of updates.

**Comment by akira0245** [comment]
oh I'm sorry! commits has been pushed. 
in recent updates i did't touch things about tones... probably i broken it at the first time trying to add standard tone mode

**Comment by bilenkonito** [comment]
No worries, I will take a look at the problem and see if I can find a solution.
