### ISSUE TITLE
New song list function - No access to OneDrive

### ISSUE THREAD

**Issue by HighlanderMisfits** [akira0245/MidiBard#38]
Previously with the older version of using Windows explorer to add songs to the song list, I was able to access any location including my cloud song storage on One Drive. Now with the integrated version I can only access local drives. I've had to move over 400 songs to my local drive so I can access them.

In addition, the old method remembers the directory you were last using, very helpful when adding songs from the same directory with multiple bards open at the time of adding the songs. Now I need to navigate each bard to the same directory and it takes longer to add a song to the list.

It would be awesome if I could simply point the plugin to a folder and it will auto pull all songs in that folder (as an option). In any case, I really would prefer to keep the songs on my One Drive location to ensure I can keep up to date backups on the cloud should anything happen to my local drives.

**Comment by akira0245** [comment]
There's an option to select file dialog type if you right click the import button, or simply copy the midifiles in explorer and ctrl+v to paste them into midibard playlist @HighlanderMisfits

**Comment by akira0245** [comment]
the folder idea is great, i'll try add it in future updates
