### ISSUE TITLE
根据音轨名称自动切换乐器

### ISSUE THREAD

**Issue by reckhou** [akira0245/MidiBard#4]
例：某首乐曲有三条音轨，可以在切换歌曲时，根据所选择音轨的名称自动切换乐器，音轨名称与游戏中乐器名称一致。为了方便和Bard Music Player兼容，电吉他的音轨名称可以分别为：ElectricGuitarClean ElectricGuitarMuted ElectricGuitarOverdriven ElectricGuitarPowerChords ElectricGuitarSpecial

如果出现选择多条音轨的情况，以排位最靠前的音轨为准。

这个功能是为了方便乐队演出，如果同时有多个bard，目前每次切换歌曲时都要手动检查并切换乐器。根据文件名切换乐器实际上在这种多人演出的情况下并不实用，当游戏重启后不同角色所保存的播放列表会相互覆盖。如果有这个功能，每个角色只要在开始时固定设置播放一条音轨，切换歌曲时就不需要再手动检查。

**Comment by akira0245** [comment]
音轨名有个问题就是文本编码不太统一，midi文件里没有任何关于音轨名采用了哪种编码的信息，各个Midi编辑软件的保存文本编码也都不一样，没法保证稳定识别，然后因为现在插件的里获取乐器名是直接读取的游戏数据，不同语言的游戏客户端里读到的乐器名也不一样，如果改用全英文的音轨名就只能硬编码

**Comment by reckhou** [comment]
应该统一使用英文比较合适，因为现在BMP的曲库里面已经有大量的曲目都是用英文的音轨名称，使用BMP标准的话应该会方便今后的兼容，如果需要的话我这边可以全部改成硬编码。

**Comment by akira0245** [comment]
已经解决
