### ISSUE TITLE
繁中語系問題

### ISSUE THREAD

**Issue by awaww333** [akira0245/MidiBard#43]
使用繁中系統都會缺字顯示問號
包括樂譜名也是  整理起來有點困擾
有辦法在後續更新補足字庫嗎 謝謝
![image](https://user-images.githubusercontent.com/74402698/149203788-42f2bde1-0313-4afd-8d7b-a6cfac95af01.png)

**Comment by akira0245** [comment]
虽然不知道繁中的卫月是哪个版本… 不过可以试着装一下同仓库下的font replacer，应该至少可以显示简中而不是问号

**Comment by awaww333** [comment]
有了  樂譜也正常顯示了  感謝！
