### ISSUE TITLE
Midibard playing all tracks

### ISSUE THREAD

**Issue by Fealow** [akira0245/MidiBard#51]
It's great that midibard is now working after the recent crashes. Good job! Upon reinstalling the plugin though I'm experiencing an odd issue where all midi tracks are being played by each bard regardless of whether I have them selected to only play a single track. Any thoughts on this?

Thanks

**Comment by akira0245** [comment]
please try the new build 1.9.2.11

**Comment by Fealow** [comment]
> 

Yup working now. thank you!
